# Spring properties
spring:
  application:
    name: CloudUi  # Identify this application
  boot:
    #Spring boot admin settings
    admin:
#      url: http://localhost:2223
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,docs
        #endpoints: env,refresh,docs
        #Timeintervalin ms to update the status of App
      monitor:
        perio: 10000
        #LifeTime of App status in ms.
        status-lifetime: 10000
        #Connection Timeout in ms when App's status and info
        connect-timeout: 2000
        #Read Timeout in ms when App's status and info
        read-timeout: 5000
      metadata-keys-to-sanitize: .password$,.*secret$,.*key$,.$token$,.credentials.,.*vcap_services$
##INFRA_ADMIN Settings
project:
  name: spring-cloud-ui
  artifactId: spring-cloud-ui
  description: spring-cloud-ui
info:
  app:
    #encoding: Encoding - EUC-KR
    encoding: Encoding - UTF-8
  java:
    source: Source - java ver
    target: Instance1 - Java ver
  spring:
    profiles: ${spring.profiles.active:default}
  build:
    name: ${project.name}
    artifact: ${project.artifactId}
    description: ${project.description}

management:     # If you set off security...
  security:
    enabled: false

